# Generated by Django 4.1.2 on 2022-10-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'CatCategoria',
                'verbose_name_plural': 'CatCategorias',
            },
        ),
        migrations.CreateModel(
            name='CatPresentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción de la presentación')),
            ],
            options={
                'verbose_name': 'CatPresentacion',
                'verbose_name_plural': 'CatPresentaciones',
            },
        ),
        migrations.CreateModel(
            name='catalogomercancia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('descripcion_producto', models.CharField(max_length=100, verbose_name='Descripción del producto')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatCategorias', to='almacen.catcategoria')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatPresentaciones', to='almacen.catpresentacion')),
            ],
            options={
                'verbose_name': 'catalogomercancia',
                'verbose_name_plural': 'catalogomercancias',
            },
        ),
    ]
