# Generated by Django 4.1.2 on 2022-10-27 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatMercancia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('descripcion_producto', models.CharField(max_length=100, verbose_name='Descripción del producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='mercancia/', verbose_name='Imagen del producto')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta de la mercancía')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la mercancía')),
            ],
            options={
                'verbose_name': 'CatMercancia',
                'verbose_name_plural': 'CatMercancias',
            },
        ),
        migrations.RemoveField(
            model_name='catcategoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='catpresentacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='catcategoria',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 27, 17, 3, 50, 815755, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta de la categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catcategoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la categoría'),
        ),
        migrations.AddField(
            model_name='catcategoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la categoría'),
        ),
        migrations.AddField(
            model_name='catpresentacion',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 27, 17, 4, 0, 87504, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta de la presentación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catpresentacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la presentación'),
        ),
        migrations.AddField(
            model_name='catpresentacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la presentación'),
        ),
        migrations.DeleteModel(
            name='catalogomercancia',
        ),
        migrations.AddField(
            model_name='catmercancia',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatCategorias', to='almacen.catcategoria'),
        ),
        migrations.AddField(
            model_name='catmercancia',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatPresentaciones', to='almacen.catpresentacion'),
        ),
    ]
