# Generated by Django 4.1.2 on 2022-10-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_catmercancia_remove_catcategoria_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catmercancia',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='catmercancia',
            name='presentacion',
        ),
        migrations.DeleteModel(
            name='CatCategoria',
        ),
        migrations.DeleteModel(
            name='CatMercancia',
        ),
        migrations.DeleteModel(
            name='CatPresentacion',
        ),
    ]
