# Generated by Django 4.1.2 on 2023-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('nota_buena', models.BooleanField(verbose_name='Buena / Mala')),
                ('cedula', models.PositiveIntegerField(verbose_name='Cédula')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'CatUsuario',
                'verbose_name_plural': 'CatUsuarios',
            },
        ),
    ]
