# Generated by Django 4.1.2 on 2023-02-14 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catusuario',
            name='rfc',
            field=models.CharField(default='##########', max_length=15, unique=True, verbose_name='RFC'),
        ),
        migrations.CreateModel(
            name='HistoricalCatUsuario',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('fecha_alta', models.DateField(blank=True, editable=False, verbose_name='Fecha de ingreso')),
                ('nota_buena', models.BooleanField(verbose_name='Buena / Mala')),
                ('cedula', models.PositiveIntegerField(verbose_name='Cédula')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rfc', models.CharField(db_index=True, default='##########', max_length=15, verbose_name='RFC')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical CatUsuario',
                'verbose_name_plural': 'historical CatUsuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCatCoordinacion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='id')),
                ('nombre_coordinacion', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de la coordinación')),
                ('nombre_area', models.CharField(choices=[('3', 'INOVACIÓN Y GESTIÓN DE CALIDAD'), ('2', 'ADMINISTRACIÓN'), ('1', 'VIGILANCIA EPIDEMIOLOGICA'), ('0', 'VIGILANCIA SANITARIA')], max_length=1, verbose_name='Nombre del área')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo / Inactivo')),
                ('fecha_alta', models.DateField(blank=True, editable=False, verbose_name='Fecha alta')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha modificacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('coordinador_responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.catusuario')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical CatCoordinacion',
                'verbose_name_plural': 'historical CatCoordinaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CatCoordinacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre_coordinacion', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la coordinación')),
                ('nombre_area', models.CharField(choices=[('3', 'INOVACIÓN Y GESTIÓN DE CALIDAD'), ('2', 'ADMINISTRACIÓN'), ('1', 'VIGILANCIA EPIDEMIOLOGICA'), ('0', 'VIGILANCIA SANITARIA')], max_length=1, verbose_name='Nombre del área')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo / Inactivo')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha alta')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificacion')),
                ('coordinador_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatPersonalLaboratorio', to='usuarios.catusuario')),
            ],
            options={
                'verbose_name': 'CatCoordinacion',
                'verbose_name_plural': 'CatCoordinaciones',
            },
        ),
    ]
