# Generated by Django 4.1.2 on 2023-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_catusuario_rfc_historicalcatusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcoordinacion',
            name='nombre_area',
            field=models.CharField(choices=[('3', 'INOVACIÓN Y GESTIÓN DE CALIDAD'), ('0', 'VIGILANCIA SANITARIA'), ('2', 'ADMINISTRACIÓN'), ('1', 'VIGILANCIA EPIDEMIOLOGICA')], max_length=1, verbose_name='Nombre del área'),
        ),
        migrations.AlterField(
            model_name='historicalcatcoordinacion',
            name='nombre_area',
            field=models.CharField(choices=[('3', 'INOVACIÓN Y GESTIÓN DE CALIDAD'), ('0', 'VIGILANCIA SANITARIA'), ('2', 'ADMINISTRACIÓN'), ('1', 'VIGILANCIA EPIDEMIOLOGICA')], max_length=1, verbose_name='Nombre del área'),
        ),
    ]
