# Generated by Django 4.1.2 on 2023-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_catcoordinacion_nombre_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcoordinacion',
            name='nombre_area',
            field=models.CharField(choices=[('1', 'VIGILANCIA EPIDEMIOLOGICA'), ('3', 'INOVACIÓN Y GESTIÓN DE CALIDAD'), ('2', 'ADMINISTRACIÓN'), ('0', 'VIGILANCIA SANITARIA')], max_length=1, verbose_name='Nombre del área'),
        ),
        migrations.AlterField(
            model_name='historicalcatcoordinacion',
            name='nombre_area',
            field=models.CharField(choices=[('1', 'VIGILANCIA EPIDEMIOLOGICA'), ('3', 'INOVACIÓN Y GESTIÓN DE CALIDAD'), ('2', 'ADMINISTRACIÓN'), ('0', 'VIGILANCIA SANITARIA')], max_length=1, verbose_name='Nombre del área'),
        ),
    ]
