# Generated by Django 4.1.2 on 2022-10-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la categoría')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta de la categoría')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la categoría')),
            ],
            options={
                'verbose_name': 'CatCategoria',
                'verbose_name_plural': 'CatCategorias',
            },
        ),
        migrations.CreateModel(
            name='CatPresentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la presentación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta de la presentación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la presentación')),
            ],
            options={
                'verbose_name': 'CatPresentacion',
                'verbose_name_plural': 'CatPresentaciones',
            },
        ),
        migrations.CreateModel(
            name='CatMercancia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('descripcion_producto', models.CharField(max_length=100, verbose_name='Descripción del producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='mercancia/', verbose_name='Imagen del producto')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta de la mercancía')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la mercancía')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatCategorias', to='catalogos.catcategoria')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatPresentaciones', to='catalogos.catpresentacion')),
            ],
            options={
                'verbose_name': 'CatMercancia',
                'verbose_name_plural': 'CatMercancias',
            },
        ),
    ]
