# Generated by Django 4.1.2 on 2022-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticulo',
            name='fecha_entrada_almacen',
            field=models.DateTimeField(default='1900-01-01T00:00', verbose_name='Fecha entrada al almacen'),
        ),
        migrations.AlterField(
            model_name='catarticulo',
            name='fecha_salida_almacen',
            field=models.DateTimeField(default='1900-01-01T00:00', verbose_name='Fecha de salida del almacen'),
        ),
        migrations.AlterField(
            model_name='historicalcatarticulo',
            name='fecha_entrada_almacen',
            field=models.DateTimeField(default='1900-01-01T00:00', verbose_name='Fecha entrada al almacen'),
        ),
        migrations.AlterField(
            model_name='historicalcatarticulo',
            name='fecha_salida_almacen',
            field=models.DateTimeField(default='1900-01-01T00:00', verbose_name='Fecha de salida del almacen'),
        ),
    ]
