# Generated by Django 4.1.2 on 2022-10-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catcategoria',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='catpresentacion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='catcategoria',
            name='nombre_categoria',
            field=models.CharField(default='N/A', max_length=50, unique=True, verbose_name='Nombre de la categoría'),
        ),
        migrations.AddField(
            model_name='catpresentacion',
            name='nombre_presentacion',
            field=models.CharField(default='N/A', max_length=50, unique=True, verbose_name='Tipo de presentación'),
        ),
        migrations.AlterField(
            model_name='catmercancia',
            name='descripcion_producto',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descripción del producto'),
        ),
    ]
