# Generated by Django 4.1.2 on 2022-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_remove_catcategoria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcategoria',
            name='nombre_categoria',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='catpresentacion',
            name='nombre_presentacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo de presentación'),
        ),
    ]
