# Generated by Django 4.1.2 on 2022-12-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_catarticulo_fecha_entrada_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catarticulo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='historicalcatarticulo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
