# Generated by Django 4.1.2 on 2022-10-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_catcategoria_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatArticulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre_articulo', models.CharField(max_length=50, unique=True, verbose_name='Nombre del artículo')),
                ('descripcion_articulo', models.TextField(verbose_name='Descripción del articulo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='mercancia/', verbose_name='Imagen del producto')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo / Inactivo')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta de la mercancía')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la mercancía')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatPresentaciones', to='catalogos.catpresentacion')),
            ],
            options={
                'verbose_name': 'CatArticulo',
                'verbose_name_plural': 'CatArticulos',
            },
        ),
        migrations.CreateModel(
            name='CatProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre_proveedor', models.CharField(max_length=50, verbose_name='Nombre del proveedor')),
                ('rfc_proveedor', models.CharField(max_length=15, unique=True, verbose_name='RFC')),
                ('calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calles')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('colonia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colonia')),
                ('codigo_postal', models.PositiveIntegerField(verbose_name='CP')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('requisicion', models.CharField(max_length=30, unique=True, verbose_name='Requisición')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo / Inactivo')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta de la mercancía')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación de la mercancía')),
            ],
            options={
                'verbose_name': 'CatProveedor',
                'verbose_name_plural': 'CatProveedores',
            },
        ),
        migrations.DeleteModel(
            name='CatMercancia',
        ),
        migrations.AddField(
            model_name='catarticulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CatProveedor', to='catalogos.catproveedor'),
        ),
    ]
