# Generated by Django 4.1.2 on 2023-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_catarticulo_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticulo',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='historicalcatarticulo',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
    ]
