# Generated by Django 4.1.2 on 2022-11-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_rename_imagen_catarticulo_exampleinputfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catarticulo',
            old_name='exampleInputFile',
            new_name='imagen',
        ),
    ]
