# Generated by Django 4.1.2 on 2022-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_rename_exampleinputfile_catarticulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catproveedor',
            name='codigo_postal',
            field=models.PositiveIntegerField(max_length=5, verbose_name='CP'),
        ),
        migrations.AlterField(
            model_name='catproveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
