# Generated by Django 4.1.2 on 2022-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_alter_catproveedor_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catproveedor',
            name='codigo_postal',
            field=models.PositiveIntegerField(verbose_name='CP'),
        ),
    ]
