# Generated by Django 4.1.2 on 2022-11-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_catproveedor_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticulo',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='articulos/', verbose_name='Imagen del producto'),
        ),
    ]
