# Generated by Django 4.1.2 on 2022-11-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_alter_catarticulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catproveedor',
            name='requisicion',
        ),
        migrations.AddField(
            model_name='catarticulo',
            name='requisicion',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Requisición'),
        ),
    ]
