# Generated by Django 4.1.2 on 2022-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_remove_catproveedor_requisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticulo',
            name='requisicion',
            field=models.CharField(default='', max_length=30, verbose_name='Requisición'),
        ),
    ]
