# Generated by Django 4.1.2 on 2022-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_catarticulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='catarticulo',
            name='fecha_entrada_almacen',
            field=models.DateTimeField(default='1981-12-10', verbose_name='Fecha entrada al almacen'),
        ),
        migrations.AddField(
            model_name='catarticulo',
            name='fecha_salida_almacen',
            field=models.DateTimeField(default='1981-12-10', verbose_name='Fecha de salida del almacen'),
        ),
    ]
