# Generated by Django 4.1.2 on 2022-11-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_catarticulo_fecha_entrada_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticulo',
            name='fecha_entrada_almacen',
            field=models.DateTimeField(default='1981-12-10T00:00:00', verbose_name='Fecha entrada al almacen'),
        ),
        migrations.AlterField(
            model_name='catarticulo',
            name='fecha_salida_almacen',
            field=models.DateTimeField(default='1981-12-10T00:00:00', verbose_name='Fecha de salida del almacen'),
        ),
    ]
