# Generated by Django 4.1.2 on 2022-11-14 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0015_alter_catarticulo_fecha_entrada_almacen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCatProveedor',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='id')),
                ('nombre_proveedor', models.CharField(max_length=50, verbose_name='Nombre del proveedor')),
                ('rfc_proveedor', models.CharField(db_index=True, max_length=15, verbose_name='RFC')),
                ('calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calles')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('colonia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colonia')),
                ('codigo_postal', models.PositiveIntegerField(verbose_name='CP')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo / Inactivo')),
                ('fecha_alta', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de alta de la mercancía')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación de la mercancía')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical CatProveedor',
                'verbose_name_plural': 'historical CatProveedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCatPresentacion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='id')),
                ('nombre_presentacion', models.CharField(db_index=True, max_length=50, verbose_name='Tipo de presentación')),
                ('fecha_alta', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de alta de la presentación')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación de la presentación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical CatPresentacion',
                'verbose_name_plural': 'historical CatPresentaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCatCategoria',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='id')),
                ('nombre_categoria', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de la categoría')),
                ('fecha_alta', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de alta de la categoría')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación de la categoría')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical CatCategoria',
                'verbose_name_plural': 'historical CatCategorias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCatArticulo',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='id')),
                ('nombre_articulo', models.CharField(db_index=True, max_length=50, verbose_name='Nombre del artículo')),
                ('descripcion_articulo', models.TextField()),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('requisicion', models.CharField(default='', max_length=30, verbose_name='Requisición')),
                ('imagen', models.TextField(blank=True, default='default/no-image.png', max_length=100, null=True, verbose_name='Imagen del producto')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo / Inactivo')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('fecha_entrada_almacen', models.DateTimeField(default='1981-12-10T00:00:00', verbose_name='Fecha entrada al almacen')),
                ('fecha_salida_almacen', models.DateTimeField(default='1981-12-10T00:00:00', verbose_name='Fecha de salida del almacen')),
                ('fecha_alta', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de alta de la mercancía')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación de la mercancía')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('presentacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.catpresentacion')),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.catproveedor')),
            ],
            options={
                'verbose_name': 'historical CatArticulo',
                'verbose_name_plural': 'historical CatArticulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
