# Generated by Django 4.1.2 on 2022-11-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_historicalcatproveedor_historicalcatpresentacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatCategoria',
        ),
        migrations.RemoveField(
            model_name='historicalcatpresentacion',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCatCategoria',
        ),
        migrations.DeleteModel(
            name='HistoricalCatPresentacion',
        ),
    ]
